version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: last_product
    ports:
      - '3307:3306' # HOST:CONTAINER
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dragonsky
      MYSQL_PASSWORD: 235711
      MYSQL_DATABASE: last_product
      TZ: Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - ./mysql/data:/var/lib/mysql
